name: atalay
description: Atalay Mobile Application
project_author: Yunus Karaaslan
project_author_email: karaaslan.21@hotmail.com
project_author_phone: +905319823347

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  flutter_native_splash: ^2.2.8
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.4
  easy_localization: ^3.0.1
  flutter_zoom_drawer: ^3.0.3
  step_progress_indicator: ^1.0.2
  calendar_view: ^1.0.0
  connectivity_plus: ^2.3.6+1
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5
  animated_shimmer: ^1.0.0
  email_validator: ^2.1.17
  image_picker: ^0.8.5+3
  flutter_settings_ui: ^2.0.1
  image_viewer:
    path: 'packages/image_viewer/'
  base_dialog:
    path: 'packages/base_dialog/'
  firebase_core: ^2.4.1
  firebase_app_installations: ^0.2.1+8
  firebase_auth: ^4.2.5
  firebase_performance: ^0.9.0+10
  firebase_crashlytics: ^3.0.11
  firebase_analytics: ^10.1.0
  firebase_in_app_messaging: ^0.7.0+10
  firebase_messaging: ^14.2.1
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  firebase_ui_firestore: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - android/app/build.gradle

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

flutter_native_splash:
  color: "#004566"
  image: assets/images/logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"